_target_: src.datamodules.lung_patch_datamodule.LungPatchH5DataModule
source_dir: /localdata/hleebg/final_project/lung_img_patches/train_A
target_dir: /localdata/hleebg/final_project/lung_img_patches/train_B
h5_key: patches
batch_size: 128
num_workers: 4
pin_memory: True
normalize: True
